services:
  nathy-gateway:
    image: joellokota/nathy-gateway:0.0.1-SNAPSHOT
    container_name: nathy-gateway
    restart: always
    ports:
      - '8084:8084'
    expose:
      - '8084'
    networks:
      - backend
  nathy-customer:
    image: joellokota/nathy-customer:0.0.1-SNAPSHOT
    container_name: nathy-customer
    restart: always
    ports:
      - '8081:8081'
    expose:
      - '8081'
    networks:
      - backend
  nathy-agency:
    image: joellokota/nathy-agency:0.0.1-SNAPSHOT
    container_name: nathy-agency
    restart: always
    ports:
      - '8082:8082'
    expose:
      - '8082'
    networks:
      - backend
  nathy-account:
    image: joellokota/nathy-account:0.0.1-SNAPSHOT
    container_name: nathy-account
    restart: always
    ports:
      - '8083:8083'
    expose:
      - '8083'
    networks:
      - backend
#  nathy-discovery:
#    image: joellokota/nathy-discovery:0.0.1-SNAPSHOT
#    container_name: nathy-discovery
#    restart: always
#    ports:
#      - '8761:8761'
#    expose:
#      - '8761'
#    networks:
#      - backend
networks:
  backend:
    name: backend
    driver: bridge