services:
  nathy-customer:
    image: joellokota/nathy-customer:0.0.3-SNAPSHOT
    container_name: nathy-customer
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx120000K
    deploy:
      resources:
        limits:
          memory: 800m
    ports:
      - '9091:9091'

  nathy-agency:
    image: joellokota/nathy-agency:0.0.3-SNAPSHOT
    container_name: nathy-agency
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx120000K
    deploy:
      resources:
        limits:
          memory: 800m
    ports:
      - '9093:9093'

  nathy-account:
    image: joellokota/nathy-account:0.0.3-SNAPSHOT
    container_name: nathy-account
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx120000K
    deploy:
      resources:
        limits:
          memory: 800m
    ports:
      - '9092:9092'

  nathy-proxy:
    image: nginx:1.27.0-alpine
    container_name: nathy-proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - ../nathy-config/agency-nathy.conf:/etc/nginx/conf.d/agency-nathy.conf
      - ../nathy-config/customer-nathy.conf:/etc/nginx/conf.d/customer-nathy.conf

#  nathy-gateway:
#    image: joellokota/nathy-gateway:0.0.3-SNAPSHOT
#    container_name: nathy-gateway
#    restart: always
#    environment:
#      - JAVA_TOOL_OPTIONS=-Xmx120000K
#    deploy:
#      resources:
#        limits:
#          memory: 800m
#    ports:
#      - '9090:9090'

#    expose:
#      - '9094'
#  nathy-discovery:
#    image: joellokota/nathy-discovery:0.0.1-SNAPSHOT
#    container_name: nathy-discovery
#    restart: always
#    ports:
#      - '8761:8761'
#    expose:
#      - '8761'
#    networks:
#      - backend