services:
  nathy-customer:
    image: joellokota/nathy-customer:0.0.3-SNAPSHOT
    container_name: nathy-customer
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx120000K
    deploy:
      resources:
        limits:
          memory: 800m
    ports:
      - '9091:9091'

  nathy-agency:
    image: joellokota/nathy-agency:0.0.3-SNAPSHOT
    container_name: nathy-agency
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx120000K
    deploy:
      resources:
        limits:
          memory: 800m
    ports:
      - '9093:9093'

  nathy-account:
    image: joellokota/nathy-account:0.0.3-SNAPSHOT
    container_name: nathy-account
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx120000K
    deploy:
      resources:
        limits:
          memory: 800m
    ports:
      - '9092:9092'

#  nathy-gateway:
#    image: joellokota/nathy-gateway:0.0.3-SNAPSHOT
#    container_name: nathy-gateway
#    restart: always
#    environment:
#      - JAVA_TOOL_OPTIONS=-Xmx120000K
#    deploy:
#      resources:
#        limits:
#          memory: 800m
#    ports:
#      - '9090:9090'

#    expose:
#      - '9094'
#  nathy-discovery:
#    image: joellokota/nathy-discovery:0.0.1-SNAPSHOT
#    container_name: nathy-discovery
#    restart: always
#    ports:
#      - '8761:8761'
#    expose:
#      - '8761'
#    networks:
#      - backend